FROM python:3.9

RUN apt install -y libpq-dev
RUN pip3 install psycopg2
RUN pip3 install Flask
RUN pip3 install flask-cors
RUN pip3 install websocket-client
RUN pip3 install rel

WORKDIR /home/scripts/
